### ISSUE TITLE
Token with 0 decimals

### ISSUE THREAD

**Issue by PhABC** [QuadrantBiosciences/QuadrantToken#3]
The Quadrant token currently is set to have 0 decimals, which can cause problems when interacting with other smart contracts since tokens with 0 decimals are not divisible (except if resultant is an integer). For instance, many decentralized exchanges charge a fee based on the tokens exchanged, taking a portion (e.g. 0.1%) of each type of token. This will result in either Quadrant tokens not being able to be exchanged over a range of centralized (yes, it can also cause problems for centralized exchanges) and decentralized exchanges, or having very expensive fees (e.g. rounded up) compared to other tokens/coins. Because of this, Quadrant tokens will not be able to be added on Etherdelta for example, and most likely many other exchanges. 

Referring to ;
https://github.com/QuadrantBiosciences/QuadrantToken/blob/master/contracts/QuadrantToken.sol

**Comment by QuadrantBiosciences** [comment]
Thanks for pointing this out. Making Quadrant Tokens indivisible is actually by design since they represent shares in Quadrant Biosciences. It is not possible to own fractions of shares, so we made the token without decimals.
